# Game settings
SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

# Player settings
PLAYER_RADIUS = 20
LINE_WIDTH = 2
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200
SHOT_RADIUS = 5
PLAYER_SHOOT_SPEED = 500
PLAYER_SHOOT_COOLDOWN_SECONDS = 0.3

# Asteroid settings
ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE_SECONDS = 0.8
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS


# Controller settings (adjust per controller if needed)
STICK_DEADZONE = 0.2
CONTROLLER_SHOOT_BUTTON = 0   # Cross / A
CONTROLLER_SHOOT_AXIS = 5     # R2 / RT
CONTROLLER_SHOOT_AXIS_THRESHOLD = 0.5
CONTROLLER_DPAD_UP = 11       # DualSense on Mac via Bluetooth
CONTROLLER_DPAD_DOWN = 12
CONTROLLER_DPAD_LEFT = 13
CONTROLLER_DPAD_RIGHT = 14
